### PR TITLE
added fastlane-snapshot

### PR DESCRIPTION
**Pull request by Aharonik1**

### CODE REVIEW

**Comment by av0c0der** [comment]
@Aharonik1 I think we need to define UITests target in Project.swift manifest. Otherwise looks good to me.

**Comment by Aharonik1** [comment]
Assalamu alaykum va rahmatullah. Tamam akhi.

**Comment by Aharonik1** [comment]
Assalamu alaykum. Brother, I've added schema and target for ui tests.

**Comment by av0c0der** [comment]
@Aharonik1 Jazakallah khayran. Looks good to me, merging into develop branch.

**Comment by Aharonik1** [comment]
> @Aharonik1 Jazakallah khayran. Looks good to me, merging into develop branch.

Va iyyaka

**Pull request merged**
